CREATE DATABASE IF NOT EXISTS sma_db;

use sma_db;

CREATE TABLE IF NOT EXISTS user (
id BIGINT PRIMARY KEY AUTO_INCREMENT,
created_at DATETIME NOT NULL DEFAULT NOW(),
first_name VARCHAR(50) NOT NULL,
last_name VARCHAR(50) NOT NULL,
email VARCHAR(50) NOT NULL UNIQUE,
password VARCHAR(100) NOT NULL,
is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS post (
id BIGINT PRIMARY KEY AUTO_INCREMENT,
created_at DATETIME NOT NULL DEFAULT NOW(),
subject VARCHAR(50) NOT NULL,
content TEXT NOT NULL,
attachment VARCHAR(50),
is_deleted BOOLEAN NOT NULL DEFAULT FALSE,

author_id BIGINT NOT NULL,
FOREIGN KEY (author_id) REFERENCES user(id)
);

CREATE TABLE IF NOT EXISTS comment (
id BIGINT PRIMARY KEY AUTO_INCREMENT,
created_at DATETIME NOT NULL DEFAULT NOW(),
content TEXT NOT NULL,
attachment VARCHAR(50),
is_deleted BOOLEAN NOT NULL DEFAULT FALSE,

post_id BIGINT NOT NULL,
author_id BIGINT NOT NULL,
FOREIGN KEY (post_id) REFERENCES post(id),
FOREIGN KEY (author_id) REFERENCES user(id)
);

CREATE TABLE IF NOT EXISTS emoji (
id BIGINT PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(50) NOT NULL 
);

CREATE TABLE IF NOT EXISTS post_reaction (
id BIGINT PRIMARY KEY AUTO_INCREMENT,
created_at DATETIME NOT NULL DEFAULT NOW(),
reactor_id BIGINT NOT NULL UNIQUE,
post_id BIGINT NOT NULL UNIQUE,
emoji_id BIGINT NOT NULL,
FOREIGN KEY (reactor_id) REFERENCES user(id),
FOREIGN KEY (post_id) REFERENCES post(id),
FOREIGN KEY (emoji_id) REFERENCES emoji(id)
);

CREATE TABLE IF NOT EXISTS comment_reaction (
id BIGINT PRIMARY KEY AUTO_INCREMENT,
created_at DATETIME NOT NULL DEFAULT NOW(),
reactor_id BIGINT NOT NULL UNIQUE,
comment_id BIGINT NOT NULL UNIQUE,
emoji_id BIGINT NOT NULL,
FOREIGN KEY (reactor_id) REFERENCES user(id),
FOREIGN KEY (comment_id) REFERENCES comment(id),
FOREIGN KEY (emoji_id) REFERENCES emoji(id)
);

INSERT INTO emoji (name)
VALUES
    ("LIKE"),
    ("HEART"),
    ("CARE"),
    ("HAHA"),
    ("WOW"),
    ("SAD"),
    ("ANGRY");
